//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HealthInsuranceEntities : DbContext
    {
        public HealthInsuranceEntities()
            : base("name=HealthInsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_HI_ADDON> TBL_HI_ADDON { get; set; }
        public virtual DbSet<TBL_HI_ADDON_PROD_MAP> TBL_HI_ADDON_PROD_MAP { get; set; }
        public virtual DbSet<TBL_HI_CAT_MST> TBL_HI_CAT_MST { get; set; }
        public virtual DbSet<TBL_HI_CLAIM_SETTLEMENT> TBL_HI_CLAIM_SETTLEMENT { get; set; }
        public virtual DbSet<TBL_HI_COMP_FILE_PATH_MST> TBL_HI_COMP_FILE_PATH_MST { get; set; }
        public virtual DbSet<TBL_HI_COMPANY> TBL_HI_COMPANY { get; set; }
        public virtual DbSet<TBL_HI_DEDUCTIBLE> TBL_HI_DEDUCTIBLE { get; set; }
        public virtual DbSet<TBL_HI_EMAIL> TBL_HI_EMAIL { get; set; }
        public virtual DbSet<TBL_HI_FEATURES> TBL_HI_FEATURES { get; set; }
        public virtual DbSet<TBL_HI_MEMBERS> TBL_HI_MEMBERS { get; set; }
        public virtual DbSet<TBL_HI_MODAL_POINTS> TBL_HI_MODAL_POINTS { get; set; }
        public virtual DbSet<TBL_HI_NETWORKHOSP> TBL_HI_NETWORKHOSP { get; set; }
        public virtual DbSet<TBL_HI_PINCODE> TBL_HI_PINCODE { get; set; }
        public virtual DbSet<TBL_HI_PROD_DEDUCTIBLE> TBL_HI_PROD_DEDUCTIBLE { get; set; }
        public virtual DbSet<TBL_HI_PROD_DESC> TBL_HI_PROD_DESC { get; set; }
        public virtual DbSet<TBL_HI_PRODUCT_CI> TBL_HI_PRODUCT_CI { get; set; }
        public virtual DbSet<TBL_HI_REGISTRATION_COMPANY> TBL_HI_REGISTRATION_COMPANY { get; set; }
        public virtual DbSet<TBL_HI_ROOM_CATEGORY> TBL_HI_ROOM_CATEGORY { get; set; }
        public virtual DbSet<TBL_HI_STATE_CITY> TBL_HI_STATE_CITY { get; set; }
        public virtual DbSet<TBL_HI_USAGE> TBL_HI_USAGE { get; set; }
        public virtual DbSet<TBL_HI_ADDON_PREM_RATES> TBL_HI_ADDON_PREM_RATES { get; set; }
        public virtual DbSet<TBL_HI_ADDON_PRODUCT_FORMULA> TBL_HI_ADDON_PRODUCT_FORMULA { get; set; }
        public virtual DbSet<TBL_HI_AGE_MST> TBL_HI_AGE_MST { get; set; }
        public virtual DbSet<TBL_HI_BENTYPE> TBL_HI_BENTYPE { get; set; }
        public virtual DbSet<TBL_HI_COPAY> TBL_HI_COPAY { get; set; }
        public virtual DbSet<TBL_HI_FAMILY> TBL_HI_FAMILY { get; set; }
        public virtual DbSet<TBL_HI_FAMILY_BKP> TBL_HI_FAMILY_BKP { get; set; }
        public virtual DbSet<TBL_HI_FAMILY_COMBO> TBL_HI_FAMILY_COMBO { get; set; }
        public virtual DbSet<TBL_HI_MEMBER_DISC> TBL_HI_MEMBER_DISC { get; set; }
        public virtual DbSet<TBL_HI_MIN_SA> TBL_HI_MIN_SA { get; set; }
        public virtual DbSet<TBL_HI_NCB> TBL_HI_NCB { get; set; }
        public virtual DbSet<TBL_HI_PREM_RATES> TBL_HI_PREM_RATES { get; set; }
        public virtual DbSet<TBL_HI_PROD_CAT> TBL_HI_PROD_CAT { get; set; }
        public virtual DbSet<TBL_HI_PROD_FAMILY> TBL_HI_PROD_FAMILY { get; set; }
        public virtual DbSet<TBL_HI_PROD_MEMBERS> TBL_HI_PROD_MEMBERS { get; set; }
        public virtual DbSet<TBL_HI_PROD_OPTION> TBL_HI_PROD_OPTION { get; set; }
        public virtual DbSet<TBL_HI_PRODUCT> TBL_HI_PRODUCT { get; set; }
        public virtual DbSet<TBL_HI_PRODUCT_FEATURES> TBL_HI_PRODUCT_FEATURES { get; set; }
        public virtual DbSet<TBL_HI_PRODUCT_FORMULA> TBL_HI_PRODUCT_FORMULA { get; set; }
        public virtual DbSet<TBL_HI_PT_MASTER> TBL_HI_PT_MASTER { get; set; }
        public virtual DbSet<TBL_HI_RATETABLE1> TBL_HI_RATETABLE1 { get; set; }
        public virtual DbSet<TBL_HI_ROOM_RENT> TBL_HI_ROOM_RENT { get; set; }
        public virtual DbSet<TBL_HI_SA_RANGE> TBL_HI_SA_RANGE { get; set; }
        public virtual DbSet<TBL_HI_STATE> TBL_HI_STATE { get; set; }
        public virtual DbSet<TBL_HI_SUBFEATURES> TBL_HI_SUBFEATURES { get; set; }
        public virtual DbSet<TBL_HI_Weights> TBL_HI_Weights { get; set; }
    
        [DbFunction("HealthInsuranceEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[HealthInsuranceEntities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("HealthInsuranceEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string @string)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[HealthInsuranceEntities].[SplitString](@String)", stringParameter);
        }
    
        public virtual ObjectResult<GetHI_FAMILY_COMBO_Result> GetHI_FAMILY_COMBO(Nullable<int> familyID)
        {
            var familyIDParameter = familyID.HasValue ?
                new ObjectParameter("familyID", familyID) :
                new ObjectParameter("familyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHI_FAMILY_COMBO_Result>("GetHI_FAMILY_COMBO", familyIDParameter);
        }
    
        public virtual ObjectResult<GetHI_MODAL_POINTS_Result> GetHI_MODAL_POINTS(Nullable<int> prodID)
        {
            var prodIDParameter = prodID.HasValue ?
                new ObjectParameter("ProdID", prodID) :
                new ObjectParameter("ProdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHI_MODAL_POINTS_Result>("GetHI_MODAL_POINTS", prodIDParameter);
        }
    
        public virtual ObjectResult<GetMasters_Result> GetMasters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMasters_Result>("GetMasters");
        }
    
        public virtual ObjectResult<Nullable<double>> HI_CalculatePremium(Nullable<int> pRODID_Input, Nullable<double> sA_ID, Nullable<double> highest_age, Nullable<int> familyid, string gender, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(double));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("Highest_age", highest_age) :
                new ObjectParameter("Highest_age", typeof(double));
    
            var familyidParameter = familyid.HasValue ?
                new ObjectParameter("familyid", familyid) :
                new ObjectParameter("familyid", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("geography", geography) :
                new ObjectParameter("geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("HI_CalculatePremium", pRODID_InputParameter, sA_IDParameter, highest_ageParameter, familyidParameter, genderParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, geographyParameter, policytermParameter, dED_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> HI_CalculatePremium_POS(Nullable<int> pRODID_Input, Nullable<double> sA_ID, Nullable<double> highest_age, Nullable<int> familyid, string gender, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(double));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("Highest_age", highest_age) :
                new ObjectParameter("Highest_age", typeof(double));
    
            var familyidParameter = familyid.HasValue ?
                new ObjectParameter("familyid", familyid) :
                new ObjectParameter("familyid", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("geography", geography) :
                new ObjectParameter("geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("HI_CalculatePremium_POS", pRODID_InputParameter, sA_IDParameter, highest_ageParameter, familyidParameter, genderParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, geographyParameter, policytermParameter, dED_IDParameter);
        }
    
        public virtual int HI_DELETEPROD(string pROD_ID)
        {
            var pROD_IDParameter = pROD_ID != null ?
                new ObjectParameter("PROD_ID", pROD_ID) :
                new ObjectParameter("PROD_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HI_DELETEPROD", pROD_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> HI_GET_COMPANY_MASTERS(Nullable<int> regID)
        {
            var regIDParameter = regID.HasValue ?
                new ObjectParameter("RegID", regID) :
                new ObjectParameter("RegID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HI_GET_COMPANY_MASTERS", regIDParameter);
        }
    
        public virtual ObjectResult<HI_GET_COMPARABLE_PRODUCT_Result> HI_GET_COMPARABLE_PRODUCT(Nullable<int> inputprod_id, Nullable<int> self_flag, Nullable<int> spouse_flag, Nullable<int> father_flag, Nullable<int> mother_flag, Nullable<int> no_children, string gender, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<double> highest_age, Nullable<int> sA_ID, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID, Nullable<int> regid)
        {
            var inputprod_idParameter = inputprod_id.HasValue ?
                new ObjectParameter("inputprod_id", inputprod_id) :
                new ObjectParameter("inputprod_id", typeof(int));
    
            var self_flagParameter = self_flag.HasValue ?
                new ObjectParameter("self_flag", self_flag) :
                new ObjectParameter("self_flag", typeof(int));
    
            var spouse_flagParameter = spouse_flag.HasValue ?
                new ObjectParameter("spouse_flag", spouse_flag) :
                new ObjectParameter("spouse_flag", typeof(int));
    
            var father_flagParameter = father_flag.HasValue ?
                new ObjectParameter("father_flag", father_flag) :
                new ObjectParameter("father_flag", typeof(int));
    
            var mother_flagParameter = mother_flag.HasValue ?
                new ObjectParameter("mother_flag", mother_flag) :
                new ObjectParameter("mother_flag", typeof(int));
    
            var no_childrenParameter = no_children.HasValue ?
                new ObjectParameter("no_children", no_children) :
                new ObjectParameter("no_children", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("highest_age", highest_age) :
                new ObjectParameter("highest_age", typeof(double));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(int));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("Geography", geography) :
                new ObjectParameter("Geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_COMPARABLE_PRODUCT_Result>("HI_GET_COMPARABLE_PRODUCT", inputprod_idParameter, self_flagParameter, spouse_flagParameter, father_flagParameter, mother_flagParameter, no_childrenParameter, genderParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, highest_ageParameter, sA_IDParameter, geographyParameter, policytermParameter, dED_IDParameter, regidParameter);
        }
    
        public virtual ObjectResult<HI_GET_FILE_NAME_PATH_Result> HI_GET_FILE_NAME_PATH(Nullable<int> pROD_ID)
        {
            var pROD_IDParameter = pROD_ID.HasValue ?
                new ObjectParameter("PROD_ID", pROD_ID) :
                new ObjectParameter("PROD_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_FILE_NAME_PATH_Result>("HI_GET_FILE_NAME_PATH", pROD_IDParameter);
        }
    
        public virtual ObjectResult<HI_GET_MASTERS_Result> HI_GET_MASTERS(string pRODUCTID)
        {
            var pRODUCTIDParameter = pRODUCTID != null ?
                new ObjectParameter("PRODUCTID", pRODUCTID) :
                new ObjectParameter("PRODUCTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_MASTERS_Result>("HI_GET_MASTERS", pRODUCTIDParameter);
        }
    
        public virtual ObjectResult<HI_GET_PROD_MASTERS_Result> HI_GET_PROD_MASTERS(string pRODUCTID)
        {
            var pRODUCTIDParameter = pRODUCTID != null ?
                new ObjectParameter("PRODUCTID", pRODUCTID) :
                new ObjectParameter("PRODUCTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PROD_MASTERS_Result>("HI_GET_PROD_MASTERS", pRODUCTIDParameter);
        }
    
        public virtual ObjectResult<HI_GET_PROD_NETWORKHOSP_Result> HI_GET_PROD_NETWORKHOSP(Nullable<int> prodID)
        {
            var prodIDParameter = prodID.HasValue ?
                new ObjectParameter("ProdID", prodID) :
                new ObjectParameter("ProdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PROD_NETWORKHOSP_Result>("HI_GET_PROD_NETWORKHOSP", prodIDParameter);
        }
    
        public virtual ObjectResult<HI_GET_PRODUCT_Result> HI_GET_PRODUCT(Nullable<int> pRODID_Input, Nullable<int> self_flag, Nullable<int> spouse_flag, Nullable<int> father_flag, Nullable<int> mother_flag, Nullable<int> no_children, string gender, Nullable<double> highest_age, Nullable<int> sA_ID, Nullable<int> dED_ID, Nullable<int> geography, Nullable<int> policyterm, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var self_flagParameter = self_flag.HasValue ?
                new ObjectParameter("self_flag", self_flag) :
                new ObjectParameter("self_flag", typeof(int));
    
            var spouse_flagParameter = spouse_flag.HasValue ?
                new ObjectParameter("spouse_flag", spouse_flag) :
                new ObjectParameter("spouse_flag", typeof(int));
    
            var father_flagParameter = father_flag.HasValue ?
                new ObjectParameter("father_flag", father_flag) :
                new ObjectParameter("father_flag", typeof(int));
    
            var mother_flagParameter = mother_flag.HasValue ?
                new ObjectParameter("mother_flag", mother_flag) :
                new ObjectParameter("mother_flag", typeof(int));
    
            var no_childrenParameter = no_children.HasValue ?
                new ObjectParameter("no_children", no_children) :
                new ObjectParameter("no_children", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("highest_age", highest_age) :
                new ObjectParameter("highest_age", typeof(double));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("Geography", geography) :
                new ObjectParameter("Geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PRODUCT_Result>("HI_GET_PRODUCT", pRODID_InputParameter, self_flagParameter, spouse_flagParameter, father_flagParameter, mother_flagParameter, no_childrenParameter, genderParameter, highest_ageParameter, sA_IDParameter, dED_IDParameter, geographyParameter, policytermParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter);
        }
    
        public virtual ObjectResult<HI_GET_PRODUCT_POS_Result> HI_GET_PRODUCT_POS(Nullable<int> pRODID_Input, Nullable<int> self_flag, Nullable<int> spouse_flag, Nullable<int> father_flag, Nullable<int> mother_flag, Nullable<int> no_children, string gender, Nullable<double> highest_age, Nullable<int> sA_ID, Nullable<int> dED_ID, Nullable<int> geography, Nullable<int> policyterm, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var self_flagParameter = self_flag.HasValue ?
                new ObjectParameter("self_flag", self_flag) :
                new ObjectParameter("self_flag", typeof(int));
    
            var spouse_flagParameter = spouse_flag.HasValue ?
                new ObjectParameter("spouse_flag", spouse_flag) :
                new ObjectParameter("spouse_flag", typeof(int));
    
            var father_flagParameter = father_flag.HasValue ?
                new ObjectParameter("father_flag", father_flag) :
                new ObjectParameter("father_flag", typeof(int));
    
            var mother_flagParameter = mother_flag.HasValue ?
                new ObjectParameter("mother_flag", mother_flag) :
                new ObjectParameter("mother_flag", typeof(int));
    
            var no_childrenParameter = no_children.HasValue ?
                new ObjectParameter("no_children", no_children) :
                new ObjectParameter("no_children", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("highest_age", highest_age) :
                new ObjectParameter("highest_age", typeof(double));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("Geography", geography) :
                new ObjectParameter("Geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PRODUCT_POS_Result>("HI_GET_PRODUCT_POS", pRODID_InputParameter, self_flagParameter, spouse_flagParameter, father_flagParameter, mother_flagParameter, no_childrenParameter, genderParameter, highest_ageParameter, sA_IDParameter, dED_IDParameter, geographyParameter, policytermParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter);
        }
    
        public virtual ObjectResult<HI_GET_PRODUCT_PRODPAGE_Result> HI_GET_PRODUCT_PRODPAGE(Nullable<int> pRODID_Input, Nullable<double> sA_ID)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PRODUCT_PRODPAGE_Result>("HI_GET_PRODUCT_PRODPAGE", pRODID_InputParameter, sA_IDParameter);
        }
    
        public virtual ObjectResult<HI_GET_PRODUCTLIST_Result> HI_GET_PRODUCTLIST(Nullable<int> self_flag, Nullable<int> spouse_flag, Nullable<int> father_flag, Nullable<int> mother_flag, Nullable<int> no_children, string gender, Nullable<double> highest_age, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> sA_ID, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5, Nullable<int> regid)
        {
            var self_flagParameter = self_flag.HasValue ?
                new ObjectParameter("self_flag", self_flag) :
                new ObjectParameter("self_flag", typeof(int));
    
            var spouse_flagParameter = spouse_flag.HasValue ?
                new ObjectParameter("spouse_flag", spouse_flag) :
                new ObjectParameter("spouse_flag", typeof(int));
    
            var father_flagParameter = father_flag.HasValue ?
                new ObjectParameter("father_flag", father_flag) :
                new ObjectParameter("father_flag", typeof(int));
    
            var mother_flagParameter = mother_flag.HasValue ?
                new ObjectParameter("mother_flag", mother_flag) :
                new ObjectParameter("mother_flag", typeof(int));
    
            var no_childrenParameter = no_children.HasValue ?
                new ObjectParameter("no_children", no_children) :
                new ObjectParameter("no_children", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("highest_age", highest_age) :
                new ObjectParameter("highest_age", typeof(double));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(int));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("Geography", geography) :
                new ObjectParameter("Geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PRODUCTLIST_Result>("HI_GET_PRODUCTLIST", self_flagParameter, spouse_flagParameter, father_flagParameter, mother_flagParameter, no_childrenParameter, genderParameter, highest_ageParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, sA_IDParameter, geographyParameter, policytermParameter, dED_IDParameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter, regidParameter);
        }
    
        public virtual ObjectResult<HI_GET_PRODUCTLIST_POS_Result> HI_GET_PRODUCTLIST_POS(Nullable<int> self_flag, Nullable<int> spouse_flag, Nullable<int> father_flag, Nullable<int> mother_flag, Nullable<int> no_children, string gender, Nullable<double> highest_age, Nullable<double> selfage, Nullable<double> spouseage, Nullable<double> motherage, Nullable<double> fatherage, Nullable<double> childage1, Nullable<double> childage2, Nullable<double> childage3, Nullable<double> childage4, Nullable<double> childage5, string childgender1, string childgender2, string childgender3, string childgender4, string childgender5, Nullable<int> sA_ID, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5, Nullable<int> regid, string inputProdId, string categoryID)
        {
            var self_flagParameter = self_flag.HasValue ?
                new ObjectParameter("self_flag", self_flag) :
                new ObjectParameter("self_flag", typeof(int));
    
            var spouse_flagParameter = spouse_flag.HasValue ?
                new ObjectParameter("spouse_flag", spouse_flag) :
                new ObjectParameter("spouse_flag", typeof(int));
    
            var father_flagParameter = father_flag.HasValue ?
                new ObjectParameter("father_flag", father_flag) :
                new ObjectParameter("father_flag", typeof(int));
    
            var mother_flagParameter = mother_flag.HasValue ?
                new ObjectParameter("mother_flag", mother_flag) :
                new ObjectParameter("mother_flag", typeof(int));
    
            var no_childrenParameter = no_children.HasValue ?
                new ObjectParameter("no_children", no_children) :
                new ObjectParameter("no_children", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("highest_age", highest_age) :
                new ObjectParameter("highest_age", typeof(double));
    
            var selfageParameter = selfage.HasValue ?
                new ObjectParameter("selfage", selfage) :
                new ObjectParameter("selfage", typeof(double));
    
            var spouseageParameter = spouseage.HasValue ?
                new ObjectParameter("spouseage", spouseage) :
                new ObjectParameter("spouseage", typeof(double));
    
            var motherageParameter = motherage.HasValue ?
                new ObjectParameter("motherage", motherage) :
                new ObjectParameter("motherage", typeof(double));
    
            var fatherageParameter = fatherage.HasValue ?
                new ObjectParameter("fatherage", fatherage) :
                new ObjectParameter("fatherage", typeof(double));
    
            var childage1Parameter = childage1.HasValue ?
                new ObjectParameter("childage1", childage1) :
                new ObjectParameter("childage1", typeof(double));
    
            var childage2Parameter = childage2.HasValue ?
                new ObjectParameter("childage2", childage2) :
                new ObjectParameter("childage2", typeof(double));
    
            var childage3Parameter = childage3.HasValue ?
                new ObjectParameter("childage3", childage3) :
                new ObjectParameter("childage3", typeof(double));
    
            var childage4Parameter = childage4.HasValue ?
                new ObjectParameter("childage4", childage4) :
                new ObjectParameter("childage4", typeof(double));
    
            var childage5Parameter = childage5.HasValue ?
                new ObjectParameter("childage5", childage5) :
                new ObjectParameter("childage5", typeof(double));
    
            var childgender1Parameter = childgender1 != null ?
                new ObjectParameter("childgender1", childgender1) :
                new ObjectParameter("childgender1", typeof(string));
    
            var childgender2Parameter = childgender2 != null ?
                new ObjectParameter("childgender2", childgender2) :
                new ObjectParameter("childgender2", typeof(string));
    
            var childgender3Parameter = childgender3 != null ?
                new ObjectParameter("childgender3", childgender3) :
                new ObjectParameter("childgender3", typeof(string));
    
            var childgender4Parameter = childgender4 != null ?
                new ObjectParameter("childgender4", childgender4) :
                new ObjectParameter("childgender4", typeof(string));
    
            var childgender5Parameter = childgender5 != null ?
                new ObjectParameter("childgender5", childgender5) :
                new ObjectParameter("childgender5", typeof(string));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(int));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("Geography", geography) :
                new ObjectParameter("Geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            var inputProdIdParameter = inputProdId != null ?
                new ObjectParameter("inputProdId", inputProdId) :
                new ObjectParameter("inputProdId", typeof(string));
    
            var categoryIDParameter = categoryID != null ?
                new ObjectParameter("categoryID", categoryID) :
                new ObjectParameter("categoryID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_PRODUCTLIST_POS_Result>("HI_GET_PRODUCTLIST_POS", self_flagParameter, spouse_flagParameter, father_flagParameter, mother_flagParameter, no_childrenParameter, genderParameter, highest_ageParameter, selfageParameter, spouseageParameter, motherageParameter, fatherageParameter, childage1Parameter, childage2Parameter, childage3Parameter, childage4Parameter, childage5Parameter, childgender1Parameter, childgender2Parameter, childgender3Parameter, childgender4Parameter, childgender5Parameter, sA_IDParameter, geographyParameter, policytermParameter, dED_IDParameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter, regidParameter, inputProdIdParameter, categoryIDParameter);
        }
    
        public virtual ObjectResult<HI_GET_SA_Graph_Result> HI_GET_SA_Graph(Nullable<int> pRODID, Nullable<decimal> sA)
        {
            var pRODIDParameter = pRODID.HasValue ?
                new ObjectParameter("PRODID", pRODID) :
                new ObjectParameter("PRODID", typeof(int));
    
            var sAParameter = sA.HasValue ?
                new ObjectParameter("SA", sA) :
                new ObjectParameter("SA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_SA_Graph_Result>("HI_GET_SA_Graph", pRODIDParameter, sAParameter);
        }
    
        public virtual ObjectResult<HI_GET_Score_Result> HI_GET_Score(Nullable<int> pRODID, Nullable<double> sA, Nullable<double> age, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5)
        {
            var pRODIDParameter = pRODID.HasValue ?
                new ObjectParameter("PRODID", pRODID) :
                new ObjectParameter("PRODID", typeof(int));
    
            var sAParameter = sA.HasValue ?
                new ObjectParameter("SA", sA) :
                new ObjectParameter("SA", typeof(double));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(double));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_GET_Score_Result>("HI_GET_Score", pRODIDParameter, sAParameter, ageParameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter);
        }
    
        public virtual ObjectResult<HI_TESTPRODUCT_Result> HI_TESTPRODUCT(Nullable<int> pRODID_Input, Nullable<double> sA_ID, Nullable<double> highest_age, Nullable<int> familyid, string gender, Nullable<int> geography, Nullable<int> policyterm, Nullable<int> dED_ID)
        {
            var pRODID_InputParameter = pRODID_Input.HasValue ?
                new ObjectParameter("PRODID_Input", pRODID_Input) :
                new ObjectParameter("PRODID_Input", typeof(int));
    
            var sA_IDParameter = sA_ID.HasValue ?
                new ObjectParameter("SA_ID", sA_ID) :
                new ObjectParameter("SA_ID", typeof(double));
    
            var highest_ageParameter = highest_age.HasValue ?
                new ObjectParameter("Highest_age", highest_age) :
                new ObjectParameter("Highest_age", typeof(double));
    
            var familyidParameter = familyid.HasValue ?
                new ObjectParameter("familyid", familyid) :
                new ObjectParameter("familyid", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var geographyParameter = geography.HasValue ?
                new ObjectParameter("geography", geography) :
                new ObjectParameter("geography", typeof(int));
    
            var policytermParameter = policyterm.HasValue ?
                new ObjectParameter("policyterm", policyterm) :
                new ObjectParameter("policyterm", typeof(int));
    
            var dED_IDParameter = dED_ID.HasValue ?
                new ObjectParameter("DED_ID", dED_ID) :
                new ObjectParameter("DED_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_TESTPRODUCT_Result>("HI_TESTPRODUCT", pRODID_InputParameter, sA_IDParameter, highest_ageParameter, familyidParameter, genderParameter, geographyParameter, policytermParameter, dED_IDParameter);
        }
    
        public virtual ObjectResult<HI_TESTScore_Result> HI_TESTScore(Nullable<int> pRODID, Nullable<double> sA, Nullable<double> age, Nullable<int> featurerank1, Nullable<int> featurerank2, Nullable<int> featurerank3, Nullable<int> featurerank4, Nullable<int> featurerank5)
        {
            var pRODIDParameter = pRODID.HasValue ?
                new ObjectParameter("PRODID", pRODID) :
                new ObjectParameter("PRODID", typeof(int));
    
            var sAParameter = sA.HasValue ?
                new ObjectParameter("SA", sA) :
                new ObjectParameter("SA", typeof(double));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(double));
    
            var featurerank1Parameter = featurerank1.HasValue ?
                new ObjectParameter("featurerank1", featurerank1) :
                new ObjectParameter("featurerank1", typeof(int));
    
            var featurerank2Parameter = featurerank2.HasValue ?
                new ObjectParameter("featurerank2", featurerank2) :
                new ObjectParameter("featurerank2", typeof(int));
    
            var featurerank3Parameter = featurerank3.HasValue ?
                new ObjectParameter("featurerank3", featurerank3) :
                new ObjectParameter("featurerank3", typeof(int));
    
            var featurerank4Parameter = featurerank4.HasValue ?
                new ObjectParameter("featurerank4", featurerank4) :
                new ObjectParameter("featurerank4", typeof(int));
    
            var featurerank5Parameter = featurerank5.HasValue ?
                new ObjectParameter("featurerank5", featurerank5) :
                new ObjectParameter("featurerank5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HI_TESTScore_Result>("HI_TESTScore", pRODIDParameter, sAParameter, ageParameter, featurerank1Parameter, featurerank2Parameter, featurerank3Parameter, featurerank4Parameter, featurerank5Parameter);
        }
    
        public virtual int ReplaceFormulas(Nullable<int> prodId)
        {
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReplaceFormulas", prodIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
