//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_PREM_RATES
    {
        public int PROD_ID { get; set; }
        public decimal AGE_LOWER_LIMIT { get; set; }
        public decimal AGE_UPPER_LIMIT { get; set; }
        public string Geography { get; set; }
        public int OPTIONS_ID { get; set; }
        public string GENDER { get; set; }
        public int FAMILY_ID { get; set; }
        public string Members_Cat { get; set; }
        public Nullable<int> PT { get; set; }
        public decimal SA_LOWER_LIMIT { get; set; }
        public decimal SA_UPPER_LIMIT { get; set; }
        public string Field1 { get; set; }
        public decimal RATE { get; set; }
    }
}
