//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_FAMILY
    {
        public int ID { get; set; }
        public int Family_ID { get; set; }
        public string Members_Cat { get; set; }
        public int No_Members { get; set; }
        public string Family_Detail { get; set; }
    }
}
