//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_PRODUCT_FEATURES
    {
        public int PROD_ID { get; set; }
        public int SubFeatureID { get; set; }
        public int Feature_Present { get; set; }
        public int OPTIONS_ID { get; set; }
        public decimal Min_SA { get; set; }
        public decimal Max_SA { get; set; }
        public double NumInfo { get; set; }
        public double MaxNumInfo { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Optional { get; set; }
        public Nullable<int> SpecialFeature { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
    }
}
