//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_ROOM_RENT
    {
        public int PROD_ID { get; set; }
        public int OPTIONS_ID { get; set; }
        public int SA_LOWER_LIMIT { get; set; }
        public int SA_UPPER_LIMIT { get; set; }
        public decimal RENT { get; set; }
        public decimal MAX_RENT_ABS { get; set; }
        public decimal RENT_SA_PERCENT { get; set; }
        public decimal MAX_RENT_SA_PERCENT { get; set; }
        public int ROOM_CATEGORY { get; set; }
    }
}
