//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_STATE_CITY
    {
        public int StateCityID { get; set; }
        public Nullable<int> StateId { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> Order_Display { get; set; }
    }
}
