//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_FEATURES
    {
        public int id { get; set; }
        public int FeaturesId { get; set; }
        public int BenID { get; set; }
        public string FeaturesName { get; set; }
        public int ComparisonFlag { get; set; }
        public string Description { get; set; }
        public string Icon_Path { get; set; }
        public string PersonalizePage_Class { get; set; }
        public Nullable<int> PersonalizePage_Order { get; set; }
    }
}
