//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_COPAY
    {
        public int PROD_ID { get; set; }
        public int OPTIONS_ID { get; set; }
        public decimal SA_LOWER_IMIT { get; set; }
        public decimal SA_UPPER_LIMIT { get; set; }
        public int AGE_LOWER { get; set; }
        public int AGE_UPPER { get; set; }
        public int ROOM_CATEGORY { get; set; }
        public decimal COPAY { get; set; }
    }
}
