//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_ROOM_CATEGORY
    {
        public int ID { get; set; }
        public int ROOM_CATEGORY { get; set; }
        public string ROOM_CAT_NAME { get; set; }
    }
}
