//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_NETWORKHOSP
    {
        public int ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public string HospName { get; set; }
        public string HospAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string LatLong { get; set; }
    }
}
