//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_PRODUCT_CI
    {
        public int id { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> FeaturesId { get; set; }
        public Nullable<int> SubFeatureID { get; set; }
        public string CIName { get; set; }
        public string CIDescription { get; set; }
    }
}
