//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_COMP_FILE_PATH_MST
    {
        public int ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public string FILE_DISPLAY_NAME { get; set; }
        public string FILE_LOCATION { get; set; }
        public string FILE_NAME_WO_EXT { get; set; }
        public string FILE_EXT { get; set; }
        public string FILE_TYPE { get; set; }
        public Nullable<System.DateTime> ADDED_DT { get; set; }
        public string FILE_STATUS { get; set; }
        public string UIN { get; set; }
    }
}
