//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_PROD_DEDUCTIBLE
    {
        public long ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<decimal> FROM_AGE { get; set; }
        public Nullable<decimal> To_AGE { get; set; }
        public Nullable<decimal> FROM_SA { get; set; }
        public Nullable<decimal> TO_SA { get; set; }
        public Nullable<decimal> Deductible { get; set; }
    }
}
