//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_NCB
    {
        public int PROD_ID { get; set; }
        public int OPTIONS_ID { get; set; }
        public decimal BONUS_RATE { get; set; }
        public decimal MAX_CUM_BONUS { get; set; }
        public int No_Years { get; set; }
        public decimal RENEWAL_DISCOUNT { get; set; }
    }
}
