//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_DEDUCTIBLE
    {
        public int ID { get; set; }
        public int DED_ID { get; set; }
        public decimal MIN_DED { get; set; }
        public decimal MAX_DED { get; set; }
        public string Description { get; set; }
    }
}
