//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_AGE_MST
    {
        public int PROD_ID { get; set; }
        public int OPTIONS_ID { get; set; }
        public int Member_ID { get; set; }
        public decimal MIN_ENTRY_AGE { get; set; }
        public decimal MAX_ENTRY_AGE { get; set; }
    }
}
