//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_CLAIM_SETTLEMENT
    {
        public long CLAIM_ID { get; set; }
        public int COMP_ID { get; set; }
        public string COMP_NAME { get; set; }
        public string Period_Name { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Ind_Group { get; set; }
        public Nullable<decimal> Opening_Claims { get; set; }
        public Nullable<decimal> New_Added { get; set; }
        public Nullable<decimal> Claims_Settled { get; set; }
        public Nullable<decimal> Claims_Repudiated { get; set; }
        public Nullable<decimal> Claims_Closed { get; set; }
        public Nullable<decimal> Closing_Claims { get; set; }
        public Nullable<decimal> Setl_1_mon { get; set; }
        public Nullable<decimal> Setl_1_3_mon { get; set; }
        public Nullable<decimal> Setl_3_6_mon { get; set; }
        public Nullable<decimal> Setl_6_12_mon { get; set; }
        public Nullable<decimal> Setl_Over_1_Yr { get; set; }
        public Nullable<decimal> Settlement_Percent { get; set; }
        public Nullable<decimal> Repudiation_Percent { get; set; }
        public Nullable<decimal> Settl_1_month_Percent { get; set; }
        public Nullable<decimal> Settl_1_3_month_Percent { get; set; }
        public Nullable<decimal> Settl_abv_3_month_Percent { get; set; }
    }
}
