//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_MEMBER_DISC
    {
        public int PROD_ID { get; set; }
        public int PT { get; set; }
        public int OPTIONS_ID { get; set; }
        public int MIN_MEMBERS { get; set; }
        public int MAX_MEMBERS { get; set; }
        public decimal SA_LOWER_LIMIT { get; set; }
        public decimal SA_UPPER_LIMIT { get; set; }
        public decimal DISC_RATE { get; set; }
    }
}
