//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_MODAL_POINTS
    {
        public int Modal_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> Family_ID { get; set; }
        public string SelfGender { get; set; }
        public Nullable<decimal> SelfAge { get; set; }
        public Nullable<decimal> SpouseAge { get; set; }
        public Nullable<decimal> FatherAge { get; set; }
        public Nullable<decimal> MotherAge { get; set; }
        public Nullable<decimal> ChildAge1 { get; set; }
        public Nullable<decimal> ChildAge2 { get; set; }
        public Nullable<decimal> ChildAge3 { get; set; }
        public Nullable<decimal> ChildAge4 { get; set; }
        public Nullable<decimal> ChildAge5 { get; set; }
        public string ChildGender1 { get; set; }
        public string ChildGender2 { get; set; }
        public string ChildGender3 { get; set; }
        public string ChildGender4 { get; set; }
        public string ChildGender5 { get; set; }
        public Nullable<int> SA_ID { get; set; }
        public Nullable<int> DED_ID { get; set; }
        public string Geography { get; set; }
    }
}
