//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_USAGE
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public string CustomerName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string FromPage { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string ProductName { get; set; }
        public string SA { get; set; }
        public string FamilyCombo { get; set; }
        public string City { get; set; }
        public string Deductible { get; set; }
    }
}
