//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace q1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HI_PRODUCT
    {
        public int PROD_ID { get; set; }
        public int COMP_ID { get; set; }
        public string PROD_NAME { get; set; }
        public int STATUS { get; set; }
    }
}
